import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Lora, Roboto } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/app/provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
});
const lora = Lora({
    subsets: ["latin"],
    variable: "--font-lora",
});
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <ReactQueryProvider>
                <body
                    className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} ${lora.variable}
                antialiased`}
                >
                    {children}
                </body>
            </ReactQueryProvider>
        </html>
    );
}
